version: "3"

services:

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - backend
    networks:
      - frontend
    healthcheck:
      test: curl -sS http://127.0.0.1:3000 || echo 1
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./lib_catalog
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend
      - backend
    healthcheck:
      test: curl -sS http://127.0.0.1:8000 || echo 1
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: "postgres:alpine3.14"
    container_name: db_2022-03-15_homework
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
       - .env
    
      
    networks:
      - frontend
      - backend
  
networks:

  frontend:
    driver: bridge

  backend:
    driver: bridge